In [202]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [203]:
df = pd.read_csv("googleplaystore.csv")
reviews = pd.read_csv("googleplaystore_user_reviews.csv")

In [204]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [205]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
App               10841 non-null object
Category          10841 non-null object
Rating            9367 non-null float64
Reviews           10841 non-null object
Size              10841 non-null object
Installs          10841 non-null object
Type              10840 non-null object
Price             10841 non-null object
Content Rating    10840 non-null object
Genres            10841 non-null object
Last Updated      10841 non-null object
Current Ver       10833 non-null object
Android Ver       10838 non-null object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [206]:
#Columns with space are Renamed
df.rename(columns = {"Content Rating":"Content_Rating", "Last Updated":"Last_Updated", "Current Ver":"Current_Ver", "Android Ver":"Android_Ver"}, inplace=True)
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [207]:
df["Category"].value_counts()

FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
LIBRARIES_AND_DEMO       85
AUTO_AND_VEHICLES        85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
1.9                       1
Name: Category, dtype: int64

In [208]:
df[df.Category == "1.9"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [209]:
df.drop(10472, axis = 0, inplace = True)

In [210]:
df["Category"].value_counts()

FAMILY                 1972
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
Name: Category, dtype: int64

In [211]:
#df["Category"] = pd.factorize(df.Category)[0]

In [212]:
reviews.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [213]:
Ap = df[df.Rating.isnull()].App
reviewsAp = reviews.App.unique()
for i in Ap:
    if i in reviewsAp:
        print(i)

Blood Pressure

In [214]:
df[df.App == "Blood Pressure"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
2310,Blood Pressure,MEDICAL,4.2,33033,7.4M,"5,000,000+",Free,0,Everyone,Medical,"July 24, 2018",3.27.3,4.1 and up
2513,Blood Pressure,MEDICAL,NaN,10,2.4M,"1,000+",Free,0,Everyone,Medical,"March 14, 2015",1.0,2.3 and up
6585,Blood Pressure,MEDICAL,4.2,33033,7.4M,"5,000,000+",Free,0,Everyone,Medical,"July 24, 2018",3.27.3,4.1 and up

In [215]:
df.iloc[2513, 2] = df[df.App == "Blood Pressure"].Rating.mean()
df[df.App == "Blood Pressure"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
2310,Blood Pressure,MEDICAL,4.2,33033,7.4M,"5,000,000+",Free,0,Everyone,Medical,"July 24, 2018",3.27.3,4.1 and up
2513,Blood Pressure,MEDICAL,4.2,10,2.4M,"1,000+",Free,0,Everyone,Medical,"March 14, 2015",1.0,2.3 and up
6585,Blood Pressure,MEDICAL,4.2,33033,7.4M,"5,000,000+",Free,0,Everyone,Medical,"July 24, 2018",3.27.3,4.1 and up

In [216]:
df.drop(list(df[df.Rating.isnull()].index), inplace = True)

In [217]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9367 entries, 0 to 10840
Data columns (total 13 columns):
App               9367 non-null object
Category          9367 non-null object
Rating            9367 non-null float64
Reviews           9367 non-null object
Size              9367 non-null object
Installs          9367 non-null object
Type              9367 non-null object
Price             9367 non-null object
Content_Rating    9367 non-null object
Genres            9367 non-null object
Last_Updated      9367 non-null object
Current_Ver       9363 non-null object
Android_Ver       9365 non-null object
dtypes: float64(1), object(12)
memory usage: 1.0+ MB

In [218]:
df.Size.unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M',
       '11M', '24M', 'Varies with device', '9.4M', '15M', '10M', '1.2M',
       '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M',
       '5.7M', '8.6M', '2.4M', '27M', '2.5M', '7.0M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '22M', '6.4M', '3.2M', '8.2M', '4.9M', '9.5M', '5.0M',
       '5.9M', '13M', '73M', '6.8M', '3.5M', '4.0M', '2.3M', '2.1M',
       '42M', '9.1M', '55M', '23k', '7.3M', '6.5M', '1.5M', '7.5M', '51M',
       '41M', '48M', '8.5M', '46M', '8.3M', '4.3M', '4.7M', '3.3M', '40M',
       '7.8M', '8.8M', '6.6M', '5.1M', '61M', '66M', '79k', '8.4M',
       '3.7M', '118k', '44M', '695k', '1.6M', '6.2M', '53M', '1.4M',
       '3.0M', '7.2M', '5.8M', '3.8M', '9.6M', '45M', '63M', '49M', '77M',
       '4.4M', '70M', '9.3M', '8.1M', '36M', '6.9M', '7.4M', '84M', '97M',
       '2.0M', '1.9M', '1.8M', '5.3M', '47M', '556k', '526k', '76M',
       '7.6M', '59M', '9.7M', '78M', '72M', '43M', '7.7M', '6.3M', '334k',
       '93M', '65M', '79M', '100M', '58M', '50M', '68M', '64M', '34M',
       '67M', '60M', '94M', '9.9M', '232k', '99M', '624k', '95M', '8.5k',
       '41k', '292k', '11k', '80M', '1.7M', '10.0M', '74M', '62M', '69M',
       '75M', '98M', '85M', '82M', '96M', '87M', '71M', '86M', '91M',
       '81M', '92M', '83M', '88M', '704k', '862k', '899k', '378k', '4.8M',
       '266k', '375k', '1.3M', '975k', '980k', '4.1M', '89M', '696k',
       '544k', '525k', '920k', '779k', '853k', '720k', '713k', '772k',
       '318k', '58k', '241k', '196k', '857k', '51k', '953k', '865k',
       '251k', '930k', '540k', '313k', '746k', '203k', '26k', '314k',
       '239k', '371k', '220k', '730k', '756k', '91k', '293k', '17k',
       '74k', '14k', '317k', '78k', '924k', '818k', '81k', '939k', '169k',
       '45k', '965k', '90M', '545k', '61k', '283k', '655k', '714k', '93k',
       '872k', '121k', '322k', '976k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '306k', '175k', '350k', '383k', '454k',
       '1.0M', '70k', '812k', '442k', '842k', '417k', '412k', '459k',
       '478k', '335k', '782k', '721k', '430k', '429k', '192k', '460k',
       '728k', '496k', '816k', '414k', '506k', '887k', '613k', '778k',
       '683k', '592k', '186k', '840k', '647k', '373k', '437k', '598k',
       '716k', '585k', '982k', '219k', '55k', '323k', '691k', '511k',
       '951k', '963k', '25k', '554k', '351k', '27k', '82k', '208k',
       '551k', '29k', '103k', '116k', '153k', '209k', '499k', '173k',
       '597k', '809k', '122k', '411k', '400k', '801k', '787k', '50k',
       '643k', '986k', '516k', '837k', '780k', '20k', '498k', '600k',
       '656k', '221k', '228k', '176k', '34k', '259k', '164k', '458k',
       '629k', '28k', '288k', '775k', '785k', '636k', '916k', '994k',
       '309k', '485k', '914k', '903k', '608k', '500k', '54k', '562k',
       '847k', '948k', '811k', '270k', '48k', '523k', '784k', '280k',
       '24k', '892k', '154k', '18k', '33k', '860k', '364k', '387k',
       '626k', '161k', '879k', '39k', '170k', '141k', '160k', '144k',
       '143k', '190k', '376k', '193k', '473k', '246k', '73k', '253k',
       '957k', '420k', '72k', '404k', '470k', '226k', '240k', '89k',
       '234k', '257k', '861k', '467k', '676k', '552k', '582k', '619k'],
      dtype=object)

In [219]:
lds = np.array(df.Size.str.find('k'))
ls = np.where(lds>0)

In [220]:
df.Size = df.Size.str.replace('M','')
df.Size = df.Size.str.replace('k','')

In [221]:
df.Size.unique()

array(['19', '14', '8.7', '25', '2.8', '5.6', '29', '33', '3.1', '28',
       '12', '20', '21', '37', '2.7', '5.5', '17', '39', '31', '4.2',
       '23', '6.0', '6.1', '4.6', '9.2', '5.2', '11', '24',
       'Varies with device', '9.4', '15', '10', '1.2', '26', '8.0', '7.9',
       '56', '57', '35', '54', '201', '3.6', '5.7', '8.6', '2.4', '27',
       '2.5', '7.0', '16', '3.4', '8.9', '3.9', '2.9', '38', '32', '5.4',
       '18', '1.1', '2.2', '4.5', '9.8', '52', '9.0', '6.7', '30', '2.6',
       '7.1', '22', '6.4', '3.2', '8.2', '4.9', '9.5', '5.0', '5.9', '13',
       '73', '6.8', '3.5', '4.0', '2.3', '2.1', '42', '9.1', '55', '7.3',
       '6.5', '1.5', '7.5', '51', '41', '48', '8.5', '46', '8.3', '4.3',
       '4.7', '3.3', '40', '7.8', '8.8', '6.6', '5.1', '61', '66', '79',
       '8.4', '3.7', '118', '44', '695', '1.6', '6.2', '53', '1.4', '3.0',
       '7.2', '5.8', '3.8', '9.6', '45', '63', '49', '77', '4.4', '70',
       '9.3', '8.1', '36', '6.9', '7.4', '84', '97', '2.0', '1.9', '1.8',
       '5.3', '47', '556', '526', '76', '7.6', '59', '9.7', '78', '72',
       '43', '7.7', '6.3', '334', '93', '65', '100', '58', '50', '68',
       '64', '34', '67', '60', '94', '9.9', '232', '99', '624', '95',
       '292', '80', '1.7', '10.0', '74', '62', '69', '75', '98', '85',
       '82', '96', '87', '71', '86', '91', '81', '92', '83', '88', '704',
       '862', '899', '378', '4.8', '266', '375', '1.3', '975', '980',
       '4.1', '89', '696', '544', '525', '920', '779', '853', '720',
       '713', '772', '318', '241', '196', '857', '953', '865', '251',
       '930', '540', '313', '746', '203', '314', '239', '371', '220',
       '730', '756', '293', '317', '924', '818', '939', '169', '965',
       '90', '545', '283', '655', '714', '872', '121', '322', '976',
       '206', '954', '444', '717', '210', '609', '308', '306', '175',
       '350', '383', '454', '1.0', '812', '442', '842', '417', '412',
       '459', '478', '335', '782', '721', '430', '429', '192', '460',
       '728', '496', '816', '414', '506', '887', '613', '778', '683',
       '592', '186', '840', '647', '373', '437', '598', '716', '585',
       '982', '219', '323', '691', '511', '951', '963', '554', '351',
       '208', '551', '103', '116', '153', '209', '499', '173', '597',
       '809', '122', '411', '400', '801', '787', '643', '986', '516',
       '837', '780', '498', '600', '656', '221', '228', '176', '259',
       '164', '458', '629', '288', '775', '785', '636', '916', '994',
       '309', '485', '914', '903', '608', '500', '562', '847', '948',
       '811', '270', '523', '784', '280', '892', '154', '860', '364',
       '387', '626', '161', '879', '170', '141', '160', '144', '143',
       '190', '376', '193', '473', '246', '253', '957', '420', '404',
       '470', '226', '240', '234', '257', '861', '467', '676', '552',
       '582', '619'], dtype=object)

In [222]:
df_temp = df.copy()

In [223]:
df_temp.drop(df[df.Size == 'Varies with device'].index,axis=0, inplace=True)

In [224]:
df_temp.Size = df_temp.Size.astype('float')

In [225]:
df.reset_index(False,inplace=True)

In [226]:
df.drop('index',axis=1, inplace=True)

In [227]:
for i,j in df.iterrows():
    if j.Size == "Varies with device":
        cat = j.Category
        df.iloc[i, 4] = df_temp.groupby('Category').Size.median()[cat]

In [228]:
df.Size = df.Size.astype("float")

In [229]:
for x in ls:
    df.iloc[x,4]=df.iloc[x,4]*0.001

In [230]:
df.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
7907,DV 2019 Entry Guide,BOOKS_AND_REFERENCE,4.5,92,5.1,"10,000+",Free,0,Everyone,Books & Reference,"October 18, 2017",2.0.0,4.1 and up
6949,Jetting for Honda CR dirt bike,SPORTS,4.1,7,3.4,100+,Paid,$3.49,Everyone,Sports,"April 13, 2016",2.2,3.0 and up
592,Live Talk - Free Text and Video Chat,DATING,4.6,185,5.0,"10,000+",Free,0,Mature 17+,Dating,"July 16, 2018",8.2,4.0.3 and up
5086,Create apps fast with beautiful design and no ...,BUSINESS,3.7,23729,24.0,"1,000,000+",Free,0,Everyone,Business,"May 14, 2018",7.2,4.4 and up
6912,Snowboard Racing Free Fun Game,GAME,3.8,4552,43.0,"100,000+",Free,0,Everyone,Racing,"October 26, 2016",1.4.0,2.3.3 and up

In [231]:
df.Installs.unique()

array(['10,000+', '500,000+', '5,000,000+', '50,000,000+', '100,000+',
       '50,000+', '1,000,000+', '10,000,000+', '5,000+', '100,000,000+',
       '1,000,000,000+', '1,000+', '500,000,000+', '100+', '500+', '10+',
       '5+', '50+', '1+'], dtype=object)

In [232]:
df.Installs = df.Installs.str.replace("+", "")
df.Installs = df.Installs.str.replace(",", "")

In [233]:
df.Installs = df.Installs.astype("int")

In [234]:
df.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
8836,EZ PZ RPG,FAMILY,3.8,70903,47.000,1000000,Free,0,Everyone 10+,Role Playing,"October 27, 2016",2.164.4,2.3 and up
3276,Flowers Live Wallpaper,PERSONALIZATION,4.1,118459,3.300,10000000,Free,0,Everyone,Personalization,"October 27, 2017",4.0,4.1 and up
8504,EP Mobile,MEDICAL,4.3,267,2.300,50000,Free,0,Everyone,Medical,"July 8, 2018",2.18,4.0 and up
5314,One Night at Golden Freddy's,GAME,3.3,2717,4.000,100000,Free,0,Teen,Action,"December 7, 2017",0.1,2.3 and up
5576,BC Lotto Check,FAMILY,3.0,10,0.717,5000,Free,0,Everyone,Entertainment,"June 22, 2016",0.0.7,4.0.3 and up

In [235]:
df.Price.unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20'], dtype=object)

In [236]:
df.Price = df.Price.str.replace("$", "")

In [237]:
df.Price = df.Price.astype("float")

In [238]:
df.sample()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
4342,Big Q Car Service,MAPS_AND_NAVIGATION,4.4,75,26.0,5000,Free,0.0,Everyone,Maps & Navigation,"May 15, 2017",3.002,4.0.3 and up

In [239]:
temp = np.array(df.Genres.str.find(';'))
ls = np.where(temp>0)

In [240]:
df2 = df.iloc[np.r_[ls],:]

In [241]:
print(df.shape)
print(df2.shape)

(9367, 13)
(483, 13)

In [242]:
df.iloc[ls[0][0:4],:]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1,10000,Free,0.0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
25,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25.0,500000,Free,0.0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up

In [243]:
df.Genres = df.Genres.apply(lambda x: x.split(';')[0])

In [244]:
df2.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1,10000,Free,0.0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up
25,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25.0,500000,Free,0.0,Everyone,Art & Design;Creativity,"October 11, 2017",1.0.8,4.0.3 and up
35,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24.0,500000,Free,0.0,Everyone,Art & Design;Creativity,"August 2, 2018",1.0.9,4.4 and up

In [245]:
df2.Genres = df2.Genres.apply(lambda x: x.split(';')[1])

In [246]:
df2.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver,Android_Ver
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Creativity,"June 20, 2018",1.1,4.4 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1,10000,Free,0.0,Everyone,Creativity,"July 3, 2018",2.8,4.0.3 and up
25,Colorfit - Drawing & Coloring,ART_AND_DESIGN,4.7,20260,25.0,500000,Free,0.0,Everyone,Creativity,"October 11, 2017",1.0.8,4.0.3 and up
35,UNICORN - Color By Number & Pixel Art Coloring,ART_AND_DESIGN,4.7,8145,24.0,500000,Free,0.0,Everyone,Creativity,"August 2, 2018",1.0.9,4.4 and up

In [247]:
df = df.append(df2, ignore_index=True)

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9850 entries, 0 to 9849
Data columns (total 13 columns):
App               9850 non-null object
Category          9850 non-null object
Rating            9850 non-null float64
Reviews           9850 non-null object
Size              9850 non-null float64
Installs          9850 non-null int32
Type              9850 non-null object
Price             9850 non-null float64
Content_Rating    9850 non-null object
Genres            9850 non-null object
Last_Updated      9850 non-null object
Current_Ver       9846 non-null object
Android_Ver       9848 non-null object
dtypes: float64(3), int32(1), object(9)
memory usage: 962.0+ KB

In [249]:
df.drop("Android_Ver",axis = 1, inplace = True)

In [250]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9850 entries, 0 to 9849
Data columns (total 12 columns):
App               9850 non-null object
Category          9850 non-null object
Rating            9850 non-null float64
Reviews           9850 non-null object
Size              9850 non-null float64
Installs          9850 non-null int32
Type              9850 non-null object
Price             9850 non-null float64
Content_Rating    9850 non-null object
Genres            9850 non-null object
Last_Updated      9850 non-null object
Current_Ver       9846 non-null object
dtypes: float64(3), int32(1), object(8)
memory usage: 885.0+ KB

In [256]:
df[df.Current_Ver == "Varies with device"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.00,50000000,Free,0.00,Teen,Art & Design,"June 8, 2018",Varies with device
36,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,9.20,5000000,Free,0.00,Everyone,Art & Design,"July 14, 2018",Varies with device
41,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,9.20,10000000,Free,0.00,Everyone,Art & Design,"July 30, 2018",Varies with device
51,Used Cars and Trucks for Sale,AUTO_AND_VEHICLES,4.6,17057,17.00,1000000,Free,0.00,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device
66,Ulysse Speedometer,AUTO_AND_VEHICLES,4.3,40211,17.00,5000000,Free,0.00,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device
67,REPUVE,AUTO_AND_VEHICLES,3.9,356,17.00,100000,Free,0.00,Everyone,Auto & Vehicles,"May 25, 2018",Varies with device
71,"Android Auto - Maps, Media, Messaging & Voice",AUTO_AND_VEHICLES,4.2,271920,16.00,10000000,Free,0.00,Teen,Auto & Vehicles,"July 11, 2018",Varies with device
84,CarMax – Cars for Sale: Search Used Car Inventory,AUTO_AND_VEHICLES,4.4,21777,17.00,1000000,Free,0.00,Everyone,Auto & Vehicles,"August 4, 2018",Varies with device
87,AutoScout24 Switzerland – Find your new car,AUTO_AND_VEHICLES,4.6,13372,17.00,1000000,Free,0.00,Everyone,Auto & Vehicles,"August 3, 2018",Varies with device
91,Fuelio: Gas log & costs,AUTO_AND_VEHICLES,4.6,65786,17.00,1000000,Free,0.00,Everyone,Auto & Vehicles,"August 2, 2018",Varies with device
101,Mirror - Zoom & Exposure -,BEAUTY,3.9,32090,12.00,1000000,Free,0.00,Everyone,Beauty,"October 24, 2016",Varies with device
108,Selfie Camera,BEAUTY,4.2,17934,12.00,1000000,Free,0.00,Everyone,Beauty,"September 12, 2017",Varies with device
115,Beauty Camera - Selfie Camera,BEAUTY,4.0,113715,12.00,10000000,Free,0.00,Everyone,Beauty,"August 3, 2017",Varies with device
116,Girls Hairstyles,BEAUTY,4.1,3595,12.00,500000,Free,0.00,Everyone,Beauty,"May 24, 2018",Varies with device
132,Wattpad 📖 Free Books,BOOKS_AND_REFERENCE,4.6,2914724,7.80,100000000,Free,0.00,Teen,Books & Reference,"August 1, 2018",Varies with device
135,Wikipedia,BOOKS_AND_REFERENCE,4.4,577550,7.80,10000000,Free,0.00,Everyone,Books & Reference,"August 2, 2018",Varies with device
136,Amazon Kindle,BOOKS_AND_REFERENCE,4.2,814080,7.80,100000000,Free,0.00,Teen,Books & Reference,"July 27, 2018",Varies with device
137,Cool Reader,BOOKS_AND_REFERENCE,4.5,246315,7.80,10000000,Free,0.00,Everyone,Books & Reference,"July 17, 2015",Varies with device
138,Dictionary - Merriam-Webster,BOOKS_AND_REFERENCE,4.5,454060,7.80,10000000,Free,0.00,Everyone,Books & Reference,"May 18, 2018",Varies with device
139,NOOK: Read eBooks & Magazines,BOOKS_AND_REFERENCE,4.5,155446,7.80,10000000,Free,0.00,Teen,Books & Reference,"April 25, 2018",Varies with device
142,FBReader: Favorite Book Reader,BOOKS_AND_REFERENCE,4.5,203130,7.80,10000000,Free,0.00,Everyone,Books & Reference,"June 28, 2018",Varies with device
145,Google Play Books,BOOKS_AND_REFERENCE,3.9,1433233,7.80,1000000000,Free,0.00,Teen,Books & Reference,"August 3, 2018",Varies with device
150,Spanish English Translator,BOOKS_AND_REFERENCE,4.2,87873,7.80,10000000,Free,0.00,Teen,Books & Reference,"May 28, 2018",Varies with device
155,NOOK App for NOOK Devices,BOOKS_AND_REFERENCE,4.7,19080,7.80,500000,Free,0.00,Everyone,Books & Reference,"April 25, 2018",Varies with device
164,Ancestry,BOOKS_AND_REFERENCE,4.3,64513,7.80,5000000,Free,0.00,Everyone,Books & Reference,"July 31, 2018",Varies with device
171,Moon+ Reader,BOOKS_AND_REFERENCE,4.4,233757,7.80,10000000,Free,0.00,Everyone,Books & Reference,"May 1, 2018",Varies with device
177,Visual Voicemail by MetroPCS,BUSINESS,4.1,16129,11.00,10000000,Free,0.00,Everyone,Business,"July 30, 2018",Varies with device
178,Indeed Job Search,BUSINESS,4.3,674730,11.00,50000000,Free,0.00,Everyone,Business,"May 21, 2018",Varies with device
179,Uber Driver,BUSINESS,4.4,1254730,11.00,10000000,Free,0.00,Everyone,Business,"August 3, 2018",Varies with device
181,Snag - Jobs Hiring Now,BUSINESS,4.3,32584,11.00,1000000,Free,0.00,Everyone,Business,"May 4, 2018",Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...
9471,Duolingo: Learn Languages Free,FAMILY,4.7,6294400,24.00,100000000,Free,0.00,Everyone,Education,"August 1, 2018",Varies with device
9472,Hot Wheels: Race Off,FAMILY,4.5,520609,24.00,10000000,Free,0.00,Everyone,Action & Adventure,"June 28, 2018",Varies with device
9478,DisneyNOW – TV Shows & Games,FAMILY,4.3,82471,24.00,5000000,Free,0.00,Everyone,Music & Video,"July 5, 2018",Varies with device
9491,Happy Street,FAMILY,4.5,110877,24.00,1000000,Free,0.00,Everyone 10+,Action & Adventure,"March 28, 2018",Varies with device
9495,School of Dragons,FAMILY,4.1,530792,24.00,10000000,Free,0.00,Everyone,Action & Adventure,"May 30, 2018",Varies with device
9505,Minion Rush: Despicable Me Official Game,FAMILY,4.5,10216997,24.00,100000000,Free,0.00,Everyone 10+,Action & Adventure,"July 12, 2018",Varies with device
9508,Hot Wheels: Race Off,FAMILY,4.5,520654,24.00,10000000,Free,0.00,Everyone,Action & Adventure,"June 28, 2018",Varies with device
9528,L.O.L. Surprise Ball Pop,FAMILY,4.3,10088,24.00,1000000,Free,0.00,Everyone,Action & Adventure,"March 8, 2018",Varies with device
9564,Toca Builders,FAMILY,4.2,3328,24.00,100000,Paid,3.99,Everyone,Creativity,"July 13, 2017",Varies with device
9566,LEGO® Friends,FAMILY,4.4,854,6.90,10000,Paid,4.99,Everyone,Pretend Play,"December 1, 2015",Varies with device
9582,Children Educational Game Full,FAMILY,4.7,30,24.00,1000,Paid,7.49,Everyone,Education,"May 16, 2018",Varies with device
9621,PlayKids - Educational cartoons and games for ...,FAMILY,4.1,182173,24.00,10000000,Free,0.00,Everyone,Music & Video,"July 30, 2018",Varies with device
9630,Duolingo: Learn Languages Free,FAMILY,4.7,6294397,24.00,100000000,Free,0.00,Everyone,Education,"August 1, 2018",Varies with device
9634,DisneyNOW – TV Shows & Games,FAMILY,4.3,82471,24.00,5000000,Free,0.00,Everyone,Music & Video,"July 5, 2018",Varies with device
9648,School of Dragons,FAMILY,4.1,530792,24.00,10000000,Free,0.00,Everyone,Action & Adventure,"May 30, 2018",Varies with device
9658,MyScript Calculator,TOOLS,4.5,342336,6.20,10000000,Free,0.00,Everyone,Education,"August 10, 2015",Varies with device
9659,My baby Piano,PARENTING,3.9,17941,12.50,5000000,Free,0.00,Everyone,Music & Video,"May 27, 2018",Varies with device
9669,Cartoon Network App,VIDEO_PLAYERS,4.0,119202,9.75,10000000,Free,0.00,Everyone 10+,Music & Video,"June 21, 2018",Varies with device
9675,Minion Rush: Despicable Me Official Game,FAMILY,4.5,10214862,24.00,100000000,Free,0.00,Everyone 10+,Action & Adventure,"July 12, 2018",Varies with device
9699,PBS KIDS Video,FAMILY,4.2,36214,24.00,5000000,Free,0.00,Everyone,Music & Video,"July 12, 2018",Varies with device
9721,LEGO ® Batman: Beyond Gotham,FAMILY,4.1,10758,8.00,100000,Paid,4.99,Everyone 10+,Action & Adventure,"December 15, 2015",Varies with device
9746,Cartoon Network App,FAMILY,4.0,119173,24.00,10000000,Free,0.00,Everyone 10+,Music & Video,"June 21, 2018",Varies with device
9765,DisneyNOW – TV Shows & Games,FAMILY,4.3,82499,24.00,5000000,Free,0.00,Everyone,Music & Video,"July 5, 2018",Varies with device
9767,Pokémon TV,FAMILY,4.2,117461,24.00,5000000,Free,0.00,Everyone,Music & Video,"June 29, 2018",Varies with device
9775,LEGO Batman: DC Super Heroes,FAMILY,4.2,2557,5.80,50000,Paid,4.99,Everyone 10+,Action & Adventure,"May 9, 2016",Varies with device
9778,Duolingo: Learn Languages Free,FAMILY,4.7,6297590,24.00,100000000,Free,0.00,Everyone,Education,"August 6, 2018",Varies with device
9784,Dr. Panda Town,FAMILY,4.0,36578,24.00,1000000,Free,0.00,Everyone,Pretend Play,"August 3, 2018",Varies with device
9796,Star Chart,FAMILY,4.3,128808,24.00,10000000,Free,0.00,Everyone,Education,"August 2, 2018",Varies with device
9814,Surprise Eggs,FAMILY,3.9,81543,24.00,10000000,Free,0.00,Everyone,Pretend Play,"July 19, 2018",Varies with device
9845,Dolphin and fish coloring book,FAMILY,3.9,2249,24.00,500000,Free,0.00,Everyone,Creativity,"May 15, 2018",Varies with device

In [257]:
ind = df[df['Current_Ver']=='Varies with device'].index

In [258]:
df_v = df.copy()

In [259]:
df_v.drop(ind, axis = 0, inplace = True)

In [260]:
df_v.Current_Ver.mode()

0    1.0
dtype: object

In [261]:
df.Current_Ver = df.Current_Ver.replace("Varies with device", "1.0")

In [263]:
df.drop_duplicates(keep='first', inplace=True)

In [264]:
df.reset_index(inplace=True)
df.drop('index',axis=1, inplace=True)
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Current_Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design,"January 15, 2018",2.0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",1.0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design,"June 20, 2018",1.1

In [265]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9296 entries, 0 to 9295
Data columns (total 12 columns):
App               9296 non-null object
Category          9296 non-null object
Rating            9296 non-null float64
Reviews           9296 non-null object
Size              9296 non-null float64
Installs          9296 non-null int32
Type              9296 non-null object
Price             9296 non-null float64
Content_Rating    9296 non-null object
Genres            9296 non-null object
Last_Updated      9296 non-null object
Current_Ver       9292 non-null object
dtypes: float64(3), int32(1), object(8)
memory usage: 835.3+ KB